#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0-or-later

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_libevm="${_lib}/libevm/libevm"
source \
  "${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_libevm}"

# shellcheck disable=SC2034
_global_variables() {
  retrieval_date=""
  call_auth=""
  wallet_name=""
  wallet_path=""
  wallet_password=""
  wallet_address=""
  wallet_seed=""
  api_key=""
  target_network=""
  rpc_selection=""
  transaction_type=""
  tx_field=""
  output_path=""
  transaction_address=""
  measure_unit=""
  retries_max=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    "evm-chains-explorers"
  _check_cmd \
    "evm-chains-info"
  _check_cmd \
    'evm-wallet'
  _check_cmd \
    "jq"
  _check_cmd \
    'node-run'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/${app_name}"
  echo \
    "${_dir}"
}

_transaction_get() {
  local \
    _type="${1}" \
    _lib \
    _cmd
  _lib="$( \
    _get_lib)/evm-transactions-tools"
  if [[ "${_type}" == "transaction" ]]; then
    _cmd="${_lib}/transaction-get"
  elif [[ "${_type}" == "receipt" ]]; then
    _cmd="${_lib}/transaction-receipt-get"
  fi
  echo \
    "${_cmd}"
}

_network_setup() {
  local \
    _chain="${1}" \
    _rpc_selection="${2}" \
    _rpc \
    _msg=()
  _msg=(
    "Looking for info on EVM blockchain"
    "'${_chain}'."
  )
  _msg_info \
    "${_msg[*]}"
  _chain_id="$( \
    evm-chains-info \
      -o \
        "id" \
      "${_chain}")"
  if [[ "${_chain_id}" != "" ]]; then
    _chain_name="$( \
      evm-chains-info \
        -o \
          "name" \
        "${_chain}" 2>/dev/null || \
        true)"
    _msg=(
      "found blockchain '${_chain_name}'"
      "with id '${_chain_id}',"
      "selecting RPC address with"
      "criterion '${_rpc_selection}'."
    )
    _msg_info \
      "${_msg[*]}"
    _rpc="$( \
      evm-chains-info \
        -o \
          "rpc" \
        -s \
          "${_rpc_selection}" \
        "${_chain}")"
  elif [[ "${_chain_id}" == "" ]]; then
    _msg=(
      "Found no known blockchain for input"
      "'${_chain}', interpreting given input"
      "as an rpc address for the selected"
      "network."
    )
    _msg_info \
      "${_msg[*]}"
    _rpc="${_chain}"
  fi
  _msg=(
    "Selected RPC address"
    "'${_rpc}'."
  )
  _msg_info \
    "${_msg[*]}"
  _network_backend="${_rpc}"
}

_evm_transaction_get() {
  local \
    _call_auth="${1}" \
    _wallet_name="${2}" \
    _wallet_path="${3}" \
    _wallet_password="${4}" \
    _wallet_seed="${5}" \
    _api_key_path="${6}" \
    _measure_unit="${7}" \
    _retries_max="${8}" \
    _network="${9}" \
    _rpc_selection="${10}" \
    _transaction_type="${11}" \
    _tx_field="${12}" \
    _output_path="${13}" \
    _transaction_address="${14}" \
    _node_run_opts=() \
    _method_args=() \
    _cmd \
    _base_args=() \
    _args=() \
    _verbose_args=() \
    _network_backend \
    _chain_id \
    _chain_name \
    _transaction \
    _msg=()
  shift \
    14
  _node_run_opts+=(
    -r
      "${_retries_max}"
  )
  _network_setup \
    "${_network}" \
    "${_rpc_selection}"
  _cmd="$( \
    _transaction_get \
      "${_transaction_type}")"
  _args+=(
    "${quiet}"
    "${_retries_max}"
    "${_wallet_seed}"
    "${_wallet_password}"
    "${_chain_id}"
    "${_chain_name}"
    "${_network_backend}"
    "${_api_key_path}"
  )
  if [[ "${_tx_field}" == "" ]]; then
    _msg=(
      "Saving output to"
      "'${_output_path}'."
    )
    _msg_info \
      "${_msg[*]}"
    _args+=(
      "${_output_path}"
    )
  elif [[ "${_tx_field}" != "" ]]; then
    _msg=(
      "You are showing verbose log"
      "together with the output."
    )
    _msg_warning \
      "${_msg[*]}"
    _args+=(
      # Only console, no output path
      ""
    )
  fi
  _args+=(
    "${_transaction_address}"
  )
  _msg=(
    "Calling '$(basename ${_cmd})'"
    "with arguments '${_args[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  node-run \
    "${_node_run_opts[@]}" \
    "${_cmd}" \
    "${_args[@]}"
}

_output_path_auto_detect() {
  local \
    _cache_dir \
    _output_dir \
    _output_path
  _cache_dir="${HOME}/.cache/${app_name}"
  _output_dir="${_cache_dir}/${target_network}/${transaction_type}"
  _output_path="${_output_dir}/${transaction_address}.json"
  mkdir \
    -p \
    "${_output_dir}" || \
    true
  chmod \
    700 \
    "${_output_dir}"
  _set_override \
    "output" \
    "path" \
    "${_output_path}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "retrieval" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "call" \
    "auth" \
    "n"
  _set_override \
    "retries" \
    "max" \
    "300"
  _set_override \
    "target" \
    "network" \
    "100"
  _set_override \
    "rpc" \
    "selection" \
    "kirsh"
  _set_override \
    "transaction" \
    "type" \
    "transaction"
  _set_override \
    "tx" \
    "field" \
    ""
  _output_path_auto_detect
  _api_key_auto_detect \
    "${target_network}"
  if [[ "${call_auth}" == "y" ]]; then
    _set_override \
      "wallet" \
      "name" \
      "default"
    _set_override \
      "wallet" \
      "path" \
      "$(_wallet_path_get \
           "${wallet_name}")"
    _secret_auto_detect \
      "seed" \
      "seed" \
      "evm-wallet" \
      "${wallet_name}"
    _secret_auto_detect \
      "password" \
      "plain" \
      "evm-wallet" \
      "${wallet_name}"
    _set_override \
      "wallet" \
      "address" \
      "$(evm-wallet \
           get \
             "${wallet_name}" \
             "address")"
  elif [[ "${call_auth}" == "n" ]]; then
    _set_override \
      "wallet" \
      "name" \
      ""
    _set_override \
      "wallet" \
      "path" \
      ""
    _set_override \
      "wallet" \
      "seed" \
      ""
    _set_override \
      "wallet" \
      "password" \
      ""
    _set_override \
      "wallet" \
      "address" \
      ""
  fi
  _set_override \
    "measure" \
    "unit" \
    "ether"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Retrieves EVM networks transactions.

Usage:
  ${app_name}
    [options]
    <transaction_address>

  networks:
    all those supported by
    'evm-chains-info' as
    well as directly RPC address

  options:
     -N <wallet_name>       EVM wallet name.
                            Default: ${wallet_name}
     -w <wallet_path>       EVM wallet file path.
                            Default: ${wallet_path}
     -p <wallet_path>       EVM wallet password file.
                            Default: ${wallet_password}
     -s <wallet_seed>       EVM wallet seed file.
                            Default: ${wallet_seed}
     -n <network>           EVM network name. Accepted values
                            are all those supported by
                            evm-chains-info and RPC addresses.
                            Default: ${target_network}
     -k <api_key>           Etherscan-like service key.
                            Default: ${api_key}
     -u <measure_unit>      Measure unit for the transaction
                            value. It can be 'ether' or 'wei'.
                            Default: ${measure_unit}
     -r <retries_max>       Maximum number of retries before
                            declaring the call failed.
                            Default: ${retries_max}
     -S <rpc_selection>     RPC selection method. It can be
                            'kirsh' or 'random'.
                            Default: ${rpc_selection}
     -t <transaction_type>  It can be 'transaction' or
                            'receipt'.
                            Default: ${transaction_type}
     -f <tx_field>          Returns a specific field from
                            the transaction.
                            Default: ${tx_field}
     -o <output_path>       If no transaction field is specified,
                            it will save the output in json format
                            at the specified location.
                            Default: ${output_path}

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_array() {
  local \
    _array=() \
    _item
  _array+=(
    "$@"
  )
  for _item \
    in "${_array[@]}"; do
  _msg_info \
    "                            ${_item}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "           Retrieval date:   ${retrieval_date}"
  _msg_info "       Authenticated call:   ${call_auth}"
  _msg_info "              Max retries:   ${retries_max}"
  _msg_info "              Wallet name:   ${wallet_name}"
  _msg_info "              Wallet path:   ${wallet_path}"
  _msg_info "          Wallet password:   ${wallet_password}"
  _msg_info "              Wallet seed:   ${wallet_seed}"
  _msg_info "                  API key:   ${api_key}"
  _msg_info "           Wallet address:   ${wallet_address}"
  _msg_info "             Measure unit:   ${measure_unit}"
  _msg_info "           Target network:   ${target_network}"
  _msg_info "     RPC selection method:   ${rpc_selection}"
  _msg_info "         Transaction type:   ${transaction_type}"
  _msg_info "        Transaction field:   ${tx_field}"
  _msg_info "              Output path:   ${output_path}"
  _msg_info "      Transaction address:   ${transaction_address}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    'aN:w:p:s:n:k:u:r:S:t:f:o:cvh?' \
    arg; do
  case \
    "${arg}" in
    a) override_call_auth="y" ;;
    N) override_wallet_name="${OPTARG}" ;;
    w) override_wallet_path="${OPTARG}" ;;
    p) override_wallet_password="${OPTARG}" ;;
    s) override_wallet_seed="${OPTARG}" ;;
    n) override_target_network="${OPTARG}" ;;
    k) override_api_key="${OPTARG}" ;;
    u) override_measure_unit="${OPTARG}" ;;
    r) override_retries_max="${OPTARG}" ;;
    S) override_rpc_selection="${OPTARG}" ;;
    t) override_transaction_type="${OPTARG}" ;;
    f) override_tx_field="${OPTARG}" ;;
    o) override_output_path="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *) _msg_error \
         "Invalid argument '${arg}'" \
         0 && \
       _usage \
         1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 ))
if (( $# < 1 )); then
  _msg_error \
    "no transaction address given" \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < $# )); then
  transaction_address="${1}"
fi
shift \
  1
_set_overrides
_show_config
app_opts=(
  "${call_auth}"
  "${wallet_name}"
  "${wallet_path}"
  "${wallet_password}"
  "${wallet_seed}"
  "${api_key}"
  "${measure_unit}"
  "${retries_max}"
  "${target_network}"
  "${rpc_selection}"
  "${transaction_type}"
  "${tx_field}"
  "${output_path}"
  "${transaction_address}"
)
_evm_transaction_get \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
