#!/usr/bin/env node

//
// SPDX-License-Identifier: AGPL-3.0-or-later
//

const
  _libcrash =
    require(
      '../libcrash-js/crash-js');
_msg_info =
  _libcrash._msg_info
_msg_error =
  _libcrash._msg_error
const
  _contract_get_module =
    require(
      './contract-get');
_contract_get =
  _contract_get_module._contract_get


function
  _global_variables() {
  app_name =
    "evm-contract-call-static";
  api_key_path =
    '';
  target_network =
    '';
  contract_address =
    '';
  contract_abi_path =
    '';
  contract_bytecode_path =
    '';
  contract_compiler_output_path =
    '';
  contract_method =
    '';
  method_args =
    [];
  quiet =
    '';
}

async function
  _contract_call_static(
    _api_key_path,
    _target_network,
    _contract_abi_path,
    _contract_bytecode_path,
    _contract_compiler_output_path,
    _contract_address,
    _contract_method,
    _method_args) {
  let
    _contract,
    _contract_get_opts,
    _method,
    _value,
    _wallet_password,
    _wallet_seed;
  _wallet_seed =
    "";
  _wallet_password =
    "";
  _contract_get_opts = [
    _wallet_seed,
    _wallet_password,
    _contract_address,
    _contract_abi_path,
    _contract_bytecode_path,
    _contract_compiler_output_path,
    _target_network,
    _api_key_path,
  ];
  _contract =
    await _contract_get.apply(
      null,
      _contract_get_opts);
  _method =
    _contract.getFunction(
      _contract_method);
  _value =
    await _method.staticCall.apply(
      null,
      _method_args);
  process.stdout.write(
    _value);
  return _value;
}

function
  _config_show() {
  let
    _line,
    _method_args,
    _text;
  _text =
    [];
  _text.push(
    "  evm-contract-call-static configuration:");
  _text.push(
    "            API Key path: {api_key_path}".replace(
      "{api_key_path}",
      api_key_path));
  _text.push(
    "          Target network: {target_network}".replace(
      "{target_network}",
      target_network));
  _text.push(
    "            Contract ABI: {contract_abi_path}".replace(
      "{contract_abi_path}",
      contract_abi_path));
  _text.push(
    "       Contract bytecode: {contract_bytecode_path}".replace(
      "{contract_bytecode_path}",
      contract_bytecode_path));
  _text.push(
    "Contract compiler output: {contract_compiler_output_path}".replace(
      "{contract_compiler_output_path}",
      contract_compiler_output_path));
  _text.push(
    "        Contract address: {contract_address}".replace(
      "{contract_address}",
      contract_address));
  _text.push(
    "         Contract method: {contract_method}".replace(
      "{contract_method}",
      contract_method));
  _method_args =
    method_args.join(
    " ");
  _text.push(
    "             Method args: {method_args}".replace(
      "{method_args}",
      _method_args));
  for (_line of _text)  { 
    _msg_info(
      _line);
  }
}

function
  _usage() {
  let
    _line,
    _text;
  _text = [
    "Execute a static call to an EVM network's contract method",
    "",
    "Usage:",
    "  evm-contract-call-static",
    "    <quiet>",
    "    <api_key_path>",
    "    <target_network>",
    "    <contract_abi_path>",
    "    <contract_bytecode_path>",
    "    <contract_compiler_output_path>",
    "    <contract_address>",
    "    <contract_method>",
    "    <method_args>",
    "",
    "Args:",
    "  <quiet>                          Can be 'y' or 'n'",
    "                                   Default: y",
    "  <api_key_path>                   Path of the API key for the",
    "                                   contract ABI provider service",
    "  <target_network>                 Network on which the contract",
    "                                   resides.",
    "  <contract_abi_path>              Path of the contract ABI",
    "  <contract_bytecode_path>         Path for the contract bytecode",
    "  <contract_compiler_output_path>  Path for the contract compiler",
    "                                   output path (the hardhat artifact).",
    "  <contract_address>               Address of the contract",
    "  <contract_method>                Contract method to execute",
    "  [method_args]                    Arguments to pass to the method",
    "",
    "  Options:",
    "    -h                             This help."
  ];
  for (_line of _text) {
    _msg_info(
      _line);
  }
}

function
  _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        api_key_path =
          _value;
      }
      if ( _index == 4 ) {
        target_network =
          _value;
      }
      if ( _index == 5 ) {
        contract_abi_path =
          _value;
      }
      if ( _index == 6 ) {
        contract_bytecode_path =
          _value;
      }
      if ( _index == 7 ) {
        contract_compiler_output_path =
          _value;
      }
      if ( _index == 8 ) {
        contract_address =
          _value;
      }
      if ( _index == 9 ) {
        contract_method =
          _value;
      }
      if ( 9 < _index ) {
        method_args.push(
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _usage();
      }
    }
  );
  if ( contract_address == "" ) {
    _usage();
  }
}


_global_variables();

if ( require.main == module ) {
  _cmdline_parse();
  _config_show();
  app_opts = [
    api_key_path,
    target_network,
    contract_abi_path,
    contract_bytecode_path,
    contract_compiler_output_path,
    contract_address,
    contract_method,
    method_args
  ];
  _contract_call_static.apply(
    null,
    app_opts);
}

module.exports = {
  _contract_call_static:
    _contract_call_static
};

